# ===============================
#        AntiKomar - Config
# ===============================

# Time (in seconds), after which alerts for a given player will be reset
alert-timeout: 300

# ===============================
#           KomarA
# ===============================
KomarA-Enable: true # Should the check be turned on?
Max-Firework-Delay: 200 # Max-Firework-Delay specifies the maximum time (in milliseconds) that can elapse between using a firework while flying an elytra and hitting another player.
Max-KomarA-Alerts: 5 # Maximum number of demerits, after that the command below will be called
KomarA-Command: "ban %player% AntiKomarSystem [KomarA]"
KomarA-Animation-Enable: false # Should animation be turned on?
KomarA-Animation-Type: NONE # ANIMATIONS: EXPLOSION | SCARY | THUNDERBOLT | GUARDIANS | LAVA | RANDOM | NONE
KomarA-Debug-Mode: false # Caution! This is only for devs only! This will spam your console and may negatively impact server performance!

# ===============================
# KomarB [DISABLED! WORK IN PROGRESS]
# ===============================
KomarB-Enable: false # This check need rewrite, and it's disabled from code [Can't enable it]
Max-KomarB-Alerts: 999
KomarB-Command: "ban %player% AntiKomarSystem [KomarB]"
KomarB-Animation-Enable: false
KomarB-Animation-Type: NONE
KomarB-Debug-Mode: false # Caution! This is only for devs only! This will spam your console and may negatively impact server performance!

# ===============================
#           KomarC
# ===============================
KomarC-Enable: true
KomarC-CriticalHitsRequired: 2
KomarC-Timeframe: 500 # Time (in milliseconds) within which critical hits must occur
Max-KomarC-Alerts: 5
KomarC-Command: "ban %player% AntiKomarSystem [KomarC]"
KomarC-Animation-Enable: false
KomarC-Animation-Type: NONE
KomarC-Debug-Mode: false  # Caution! This is only for devs only! This will spam your console and may negatively impact server performance!

# ===============================
#        Discord WebHook
# ===============================
discord:
  enabled: false
  discord-webhook-url: "https://discord.com/api/webhooks/..."
  username: "DuckyAntiKomar"
  avatar-url: "https://i.imgur.com/wPfoYdI.png"
  violation-message-template: "**AntiKomarSystem**\nPlayer: **%player%**\nCheck: **%check%**\nViolation: **%vl%**"
  animation-play-message-template: "**Animation Played**\nPlayer: **%player%**\nAnimation: **%animation%**"
  punishment-message-template: "**Punishment Executed**\nPlayer: **%player%**\nCommand: `%command%`"

# ===============================
#           Permissions
# ===============================
permissions:
  alerts: "antikomar.alerts"
  bypass: "antikomar.bypass"
  reload: "anitkomar.reload"
# Please note that the permissions section is for information purposes only.
# Changing this will not change the permissions in the plugin!