# ===============================
#        AntiKomar - Config
# ===============================

# Time (in seconds), after which alerts for a given player will be reset
alert-timeout: 300

# ===============================
#           KomarA
# ===============================
KomarA-Enable: true
Max-Firework-Delay: 100 # Max-Firework-Delay specifies the maximum time (in milliseconds) that can elapse between using a firework while flying an elytra and hitting another player.
Max-KomarA-Alerts: 5
KomarA-Command: "ban %player% AntiKomarSystem [KomarA]"
KomarA-Debug-Mode: false # Caution! This is only for devs only! This will spam your console and may negatively impact server performance!

# ===============================
# KomarB [DISABLED! WORK IN PROGRESS]
# ===============================
KomarB-Enable: false # This check need rewrite, and it's disabled from code [Can't enable it]
Max-KomarB-Alerts: 999
KomarB-Command: "ban %player% AntiKomarSystem [KomarB]"
KomarB-Debug-Mode: false # Caution! This is only for devs only! This will spam your console and may negatively impact server performance!

# ===============================
#           KomarC
# ===============================
KomarC-Enable: true
KomarC-CriticalHitsRequired: 3
KomarC-Timeframe: 300 # Time (in milliseconds) within which critical hits must occur
Max-KomarC-Alerts: 5
KomarC-Command: "ban %player% AntiKomarSystem [KomarD]"
KomarC-Debug-Mode: false  # Caution! This is only for devs only! This will spam your console and may negatively impact server performance!



# ===============================
# Elytra maximum speeds [KomarB]
# ===============================
elytra-speeds:
above-max-speed-gliding: 282.6
above-max-speed-boost: 128.6
above-max-speed-pitch-10: 240.0
above-max-speed-pitch-50: 200.0
above-max-speed-pitch-54: 242.3
above-max-speed-pitch-87: 282.4
above-max-speed-pitch-90: 282.6
above-max-speed-pitch-92: 300.0
above-max-speed-pitch-100: 320.0

# ===============================
#        Discord WebHook
# ===============================
discord:
  enabled: false  # Enable webhooks?
  discord-webhook-url: "https://discord.com/api/webhooks/..."  # Your Webhook URL (insert valid webhook URL here)
  username: "DuckyAntiKomar"  # Username displayed in webhook
  avatar-url: "https://i.imgur.com/wPfoYdI.png"  # Avatar URL (optional)
  message-template: "**AntiKomarSystem**\nPlayer: **%player%**\nCheck: **%check%**\nViolation: **%vl%**" # Message template, %player%, %check%, %vl% are replaced dynamically

# ===============================
#           Permissions
# ===============================
permissions:
  alerts: "antikomar.alerts"
  bypass: "antikomar.bypass"
  reload: "anitkomar.reload"
# Please note that the permissions section is for information purposes only.
# Changing this will not change the permissions in the plugin!